<?xml version="1.0" encoding="utf-8"?>
<robot name="smallbot"
	xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Matherials -->
	<xacro:include filename="$(find smallbot_description)/urdf/smallbot_materials.xacro" />
    <!-- Gazebo parameters -->
    <xacro:include filename="$(find smallbot_description)/urdf/smallbot.gazebo" />
    <xacro:property name="clearance" value="0.035" />
    <xacro:property name="wheel_radius" value="0.035"/>
    <xacro:property name="wheel_separation" value="0.15"/>
    <xacro:property name="wheel_width" value="0.035"/>
    <xacro:property name="mass" value="0.1"/>
    <xacro:property name="wheel_mass" value="0.2"/>
    <xacro:property name="marker_mass" value="0.0"/>
    <xacro:property name="inertia" value="1.0"/>
    <xacro:property name="PI" value="3.1415926"/>
    <xacro:property name="wheel_ixx" value="${wheel_mass*(3*wheel_radius*wheel_radius+wheel_width*wheel_width)/12}" />
    <xacro:property name="wheel_ixy" value="0.0" />
    <xacro:property name="wheel_ixz" value="0.0" />
    <xacro:property name="wheel_iyy" value="${wheel_mass*(3*wheel_radius*wheel_radius+wheel_width*wheel_width)/12}" />
    <xacro:property name="wheel_iyz" value="0.0" />
    <xacro:property name="wheel_izz" value="${wheel_mass*wheel_radius*wheel_radius/2}" />
	<!-- smallbot_base -->
    <link name="base_link">
    </link>
	<link name="body_link">
		<visual>
			<origin xyz="0 0 0.03" rpy="0 0 0" />
            <geometry>
                <box size="0.28 ${wheel_separation} 0.08"/>
            </geometry>
			<material name="White" />
		</visual>
		<collision>
			<origin xyz="0 0 0.03" rpy="0 0 0" />
            <geometry>
                <box size="0.28 ${wheel_separation} 0.08"/>
            </geometry>
		</collision>
        <inertial>
            <origin xyz="0 0 0.03" rpy="0 0 0" />
            <mass value="${mass}" />
            <inertia ixx="${inertia}" ixy="0.0" ixz="0.0" iyy="${inertia}" iyz="0.0" izz="${inertia}" />
        </inertial>
	</link>
    <joint name="base_to_body" type="fixed">
        <axis rpy="0 0 0" xyz="0 0 0"/>
        <parent link="base_link" />
        <child link="body_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>
    <link name="rear_left_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${wheel_mass}" />
            <inertia ixx="${wheel_ixx}" ixy="${wheel_ixy}" ixz="${wheel_ixz}" iyy="${wheel_iyy}" iyz="${wheel_iyz}" izz="${wheel_izz}" />
        </inertial>
    </link>
    <link name="rear_left_wheel_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <link name="rear_right_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${wheel_mass}" />
            <inertia ixx="${wheel_ixx}" ixy="${wheel_ixy}" ixz="${wheel_ixz}" iyy="${wheel_iyy}" iyz="${wheel_iyz}" izz="${wheel_izz}" />
        </inertial>
    </link>
    <link name="rear_right_wheel_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <link name="front_left_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${wheel_mass}" />
            <inertia ixx="${wheel_ixx}" ixy="${wheel_ixy}" ixz="${wheel_ixz}" iyy="${wheel_iyy}" iyz="${wheel_iyz}" izz="${wheel_izz}" />
        </inertial>
    </link>
    <link name="front_left_wheel_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <link name="front_right_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${wheel_mass}" />
            <inertia ixx="${wheel_ixx}" ixy="${wheel_ixy}" ixz="${wheel_ixz}" iyy="${wheel_iyy}" iyz="${wheel_iyz}" izz="${wheel_izz}" />
        </inertial>
    </link>
    <link name="front_right_wheel_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <link name="middle_left_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${wheel_mass}" />
            <inertia ixx="${wheel_ixx}" ixy="${wheel_ixy}" ixz="${wheel_ixz}" iyy="${wheel_iyy}" iyz="${wheel_iyz}" izz="${wheel_izz}" />
        </inertial>
    </link>
    <link name="middle_left_wheel_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <link name="middle_right_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${wheel_mass}" />
            <inertia ixx="${wheel_ixx}" ixy="${wheel_ixy}" ixz="${wheel_ixz}" iyy="${wheel_iyy}" iyz="${wheel_iyz}" izz="${wheel_izz}" />
        </inertial>
    </link>
    <link name="middle_right_wheel_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <joint name="base_to_rear_left_wheel" type="continuous">
        <axis rpy="0 0 0" xyz="0 1 0"/>
        <parent link="body_link" />
        <child link="rear_left_wheel" />
        <origin xyz="-0.104 ${wheel_separation/2 + wheel_width/2} 0" rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <limit effort= "100" velocity="100"/>
    </joint>
    <joint name="base_to_rear_right_wheel" type="continuous">
        <axis rpy="0 0 0" xyz="0 1 0"/>
        <parent link="body_link" />
        <child link="rear_right_wheel" />
		<origin xyz="-0.104 ${-1 * (wheel_separation/2 + wheel_width/2)} 0" rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>
        <limit effort= "100" velocity="100"/>
    </joint>
    <joint name="base_to_front_left_wheel" type="continuous">
        <axis rpy="0 0 0" xyz="0 1 0"/>
        <parent link="body_link" />
        <child link="front_left_wheel" />
		<origin xyz="0.104 ${wheel_separation/2 + wheel_width/2} 0" rpy="0 0 0" />
        <dynamics damping="0.0" friction="0.0"/>
        <limit effort= "100" velocity="100"/>
    </joint>
    <joint name="base_to_front_right_wheel" type="continuous">
        <axis rpy="0 0 0" xyz="0 1 0"/>
        <parent link="body_link" />
        <child link="front_right_wheel" />
		<origin xyz="0.104 ${-1 * (wheel_separation/2 + wheel_width/2)} 0" rpy="0 0 0" />
        <dynamics damping="0.0" friction="0.0"/>
        <limit effort= "100" velocity="100"/>
    </joint>
    <joint name="base_to_middle_left_wheel" type="continuous">
        <axis rpy="0 0 0" xyz="0 1 0"/>
        <parent link="body_link" />
        <child link="middle_left_wheel" />
		<origin xyz="0 ${wheel_separation/2 + wheel_width/2} 0" rpy="0 0 0" />
        <dynamics damping="0.0" friction="0.0"/>
        <limit effort= "100" velocity="100"/>
    </joint>
    <joint name="base_to_middle_right_wheel" type="continuous">
        <axis rpy="0 0 0" xyz="0 1 0"/>
        <parent link="body_link" />
        <child link="middle_right_wheel" />
		<origin xyz="0 ${-1 * (wheel_separation/2 + wheel_width/2)} 0" rpy="0 0 0" />
        <dynamics damping="0.0" friction="0.0"/>
        <limit effort= "100" velocity="100"/>
    </joint>
    <joint name="rear_left_wheel_to_marker" type="fixed">
        <parent link="rear_left_wheel" />
        <child link="rear_left_wheel_marker" />
        <origin xyz="0.015 0.0175 0" rpy="0 0 0" />
    </joint>
    <joint name="rear_right_wheel_to_marker" type="fixed">
        <parent link="rear_right_wheel" />
        <child link="rear_right_wheel_marker" />
        <origin xyz="0.015 -0.0175 0" rpy="0 0 0" />
    </joint>
    <joint name="front_left_wheel_to_marker" type="fixed">
        <parent link="front_left_wheel" />
        <child link="front_left_wheel_marker" />
        <origin xyz="0.015 0.0175 0" rpy="0 0 0" />
    </joint>
    <joint name="front_right_wheel_to_marker" type="fixed">
        <parent link="front_right_wheel" />
        <child link="front_right_wheel_marker" />
        <origin xyz="0.015 -0.0175 0" rpy="0 0 0" />
    </joint>
    <joint name="middle_left_wheel_to_marker" type="fixed">
        <parent link="middle_left_wheel" />
        <child link="middle_left_wheel_marker" />
        <origin xyz="0.015 0.0175 0" rpy="0 0 0" />
    </joint>
    <joint name="middle_right_wheel_to_marker" type="fixed">
        <parent link="middle_right_wheel" />
        <child link="middle_right_wheel_marker" />
        <origin xyz="0.015 -0.0175 0" rpy="0 0 0" />
    </joint>
</robot>
